language: python
python:
- 2.6
- 2.7
- 3.3
- pypy
services:
  - redis-server
install:
- pip install -e .
- pip install pytest
script:
- py.test
notifications:
  irc:
    channels:
    - "irc.freenode.net#sider"
    on_success: change
    on_failure: always
