language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- pypy
services:
- redis-server
install:
- pip install -e .
- pip install pytest pytest-cov coveralls
script:
- py.test -vv --cov sider --durations=20
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.freenode.net#sider"
    on_success: change
    on_failure: always
